/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhony Espinoza
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form FormularioB
     */
    public Formulario() {
        initComponents();
        inicializarTabla();
        setLocationRelativeTo(null);
    }

    public void inicializarTabla() {
        String[] columnas = {"Nombre", "Curso", "Carrera", "Sexo", "Cedula", "Correo"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0); // ✅ La tabla empieza sin filas pero con columnas definidas 
        TableReportes.setModel(modelo);
        jTable1.setModel(modelo);
        jTableEdit.setModel(modelo);
    }

    public JTable getTable1() {
        return jTable1;
    }

    public JTable getjTableEdit() {
        return jTableEdit;
    }

    public JTable getTableReportes() {
        return TableReportes;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextField getTxtCurso() {
        return txtCurso;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JComboBox<String> getComboBoxCarrera() {
        return ComboBoxCarrera;
    }

    public ButtonGroup getGrupoSexo() {
        return buttonGroup1;
    }

    public String getSelectedSexo() {
        if (RadioButtonMasculino.isSelected()) {
            return "Masculino";
        }
        if (RadioButtonFemenino.isSelected()) {
            return "Femenino";
        }
        return "No seleccionado";
    }

    public JTabbedPane getTabPanel() {
        return jTbbPEditar; // Asegúrate que el nombre coincida
    }

    public JTextField getTxtNombreEdit() {
        return txtNombreEdit;
    }

    public JTextField getTxtCedulaEdit() {
        return txtCedulaEdit;
    }

    public JTextField getTxtCursoEdit() {
        return txtCursoEdit;
    }

    public JTextField getTxtCorreoEdit() {
        return txtCorreoEdit;
    }

    public JComboBox<String> getComboBoxCarreraEdit() {
        return ComboBoxCarreraEdit;
    }

    public ButtonGroup getGrupoSexoEdit() {
        return buttonGroupEdit;
    }

    public String getSelectedSexoEdit() {
        if (RadioButtonMasculinoEdit.isSelected()) {
            return "Masculino";
        }
        if (RadioButtonFemeninoEdit.isSelected()) {
            return "Femenino";
        }
        return "No seleccionado";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupEdit = new javax.swing.ButtonGroup();
        jTbbPEditar = new javax.swing.JTabbedPane();
        PanelAlumno = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        ComboBoxCarrera = new javax.swing.JComboBox<>();
        lblsexo = new javax.swing.JLabel();
        RadioButtonMasculino = new javax.swing.JRadioButton();
        RadioButtonFemenino = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLbCedula = new javax.swing.JLabel();
        jLbCorreo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblnombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPEditar = new javax.swing.JPanel();
        PanelEditar = new javax.swing.JPanel();
        lblCursoEdit = new javax.swing.JLabel();
        lblCarreraEdit = new javax.swing.JLabel();
        txtCursoEdit = new javax.swing.JTextField();
        ComboBoxCarreraEdit = new javax.swing.JComboBox<>();
        lblsexoEdit = new javax.swing.JLabel();
        RadioButtonMasculinoEdit = new javax.swing.JRadioButton();
        RadioButtonFemeninoEdit = new javax.swing.JRadioButton();
        btnGuardarEdit = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLbCedulaEdit = new javax.swing.JLabel();
        jLbCorreoEdit = new javax.swing.JLabel();
        txtCedulaEdit = new javax.swing.JTextField();
        txtCorreoEdit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEdit = new javax.swing.JTable();
        lblnombreEdit = new javax.swing.JLabel();
        txtNombreEdit = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        PanelReportes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTbbPEditar.setToolTipText("");

        lblCurso.setText("Curso:");

        lblCarrera.setText("Carrera:");

        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });

        ComboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarollo Software", "Big Data", "Cyberseguridad", "Mecatronica", "Tributacion", "Produccion Audiovisual", "Entrenamiento Deportivo" }));

        lblsexo.setText("Sexo:");

        buttonGroup1.add(RadioButtonMasculino);
        RadioButtonMasculino.setText("Masculino");

        buttonGroup1.add(RadioButtonFemenino);
        RadioButtonFemenino.setSelected(true);
        RadioButtonFemenino.setText("Femenino");
        RadioButtonFemenino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnGuardar.setText("Guardar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLbCedula.setText("Cedula:");

        jLbCorreo.setText("Correo:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lblnombre.setText("Nombre:");

        javax.swing.GroupLayout PanelAlumnoLayout = new javax.swing.GroupLayout(PanelAlumno);
        PanelAlumno.setLayout(PanelAlumnoLayout);
        PanelAlumnoLayout.setHorizontalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCurso)
                                    .addComponent(lblCarrera))
                                .addGap(18, 18, 18)
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblsexo)
                                    .addComponent(jLbCorreo)))
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLbCedula)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblnombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addComponent(RadioButtonMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonFemenino))
                            .addComponent(txtNombre)))
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(259, 259, 259)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAlumnoLayout.setVerticalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbCedula)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurso)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarrera)
                    .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblsexo)
                        .addComponent(RadioButtonMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RadioButtonFemenino)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTbbPEditar.addTab("Registrar Alumno", PanelAlumno);

        lblCursoEdit.setText("Curso:");

        lblCarreraEdit.setText("Carrera:");

        ComboBoxCarreraEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarollo Software", "Big Data", "Cyberseguridad", "Mecatronica", "Tributacion", "Produccion Audiovisual", "Entrenamiento Deportivo" }));

        lblsexoEdit.setText("Sexo:");

        buttonGroupEdit.add(RadioButtonMasculinoEdit);
        RadioButtonMasculinoEdit.setText("Masculino");

        buttonGroupEdit.add(RadioButtonFemeninoEdit);
        RadioButtonFemeninoEdit.setText("Femenino");
        RadioButtonFemeninoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFemeninoEditActionPerformed(evt);
            }
        });

        btnGuardarEdit.setText("Guardar Cambios");
        btnGuardarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLbCedulaEdit.setText("Cedula:");

        jLbCorreoEdit.setText("Correo:");

        txtCedulaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaEditActionPerformed(evt);
            }
        });

        jTableEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEdit);

        lblnombreEdit.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelEditarLayout.createSequentialGroup()
                                        .addComponent(jLbCedulaEdit)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCedulaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelEditarLayout.createSequentialGroup()
                                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCursoEdit)
                                            .addComponent(lblCarreraEdit))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCursoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxCarreraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnBuscar)))
                        .addGap(84, 84, 84)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsexoEdit)
                            .addComponent(jLbCorreoEdit)
                            .addComponent(lblnombreEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addComponent(RadioButtonMasculinoEdit)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonFemeninoEdit))
                            .addComponent(txtNombreEdit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(btnGuardarEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombreEdit)
                            .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbCorreoEdit)
                            .addComponent(txtCorreoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsexoEdit)
                            .addComponent(RadioButtonMasculinoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonFemeninoEdit))
                        .addGap(60, 60, 60))
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbCedulaEdit)
                            .addComponent(txtCedulaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCursoEdit)
                            .addComponent(txtCursoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarreraEdit)
                            .addComponent(ComboBoxCarreraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addComponent(PanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTbbPEditar.addTab("Editar o Eliminar ", jPEditar);

        TableReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableReportes);

        jLabel1.setText("Estudiantes Registrados");

        javax.swing.GroupLayout PanelReportesLayout = new javax.swing.GroupLayout(PanelReportes);
        PanelReportes.setLayout(PanelReportesLayout);
        PanelReportesLayout.setHorizontalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(489, Short.MAX_VALUE))
            .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelReportesLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        PanelReportesLayout.setVerticalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelReportesLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        jTbbPEditar.addTab("Reportes", PanelReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbbPEditar, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTbbPEditar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void RadioButtonFemeninoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFemeninoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonFemeninoEditActionPerformed

    private void btnGuardarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEditActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void txtCedulaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaEditActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxCarrera;
    public javax.swing.JComboBox<String> ComboBoxCarreraEdit;
    public javax.swing.JPanel PanelAlumno;
    public javax.swing.JPanel PanelEditar;
    public javax.swing.JPanel PanelReportes;
    public javax.swing.JRadioButton RadioButtonFemenino;
    public javax.swing.JRadioButton RadioButtonFemeninoEdit;
    public javax.swing.JRadioButton RadioButtonMasculino;
    public javax.swing.JRadioButton RadioButtonMasculinoEdit;
    public javax.swing.JTable TableReportes;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnGuardarEdit;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSalir1;
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbCedula;
    private javax.swing.JLabel jLbCedulaEdit;
    private javax.swing.JLabel jLbCorreo;
    private javax.swing.JLabel jLbCorreoEdit;
    public javax.swing.JPanel jPEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTableEdit;
    public javax.swing.JTabbedPane jTbbPEditar;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCarreraEdit;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblCursoEdit;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombreEdit;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lblsexoEdit;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCedulaEdit;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtCorreoEdit;
    public javax.swing.JTextField txtCurso;
    public javax.swing.JTextField txtCursoEdit;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreEdit;
    // End of variables declaration//GEN-END:variables
}
